version: '3.8'

services:
  postgres:
    image: 'postgres:13-alpine'
    restart: always
    environment:
      POSTGRES_USER: ${APP_DATABASE_USER:-webform}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD:-webform}
      POSTGRES_DB: ${APP_DATABASE_NAME:-webform}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres

  rails:
    image: ${APP_IMAGE:-<APP_IMAGE>}
    # build: .
    restart: always
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
      RAILS_ENV: ${PROJECT_ENVIRONMENT:-production}
      NODE_ENV: ${PROJECT_ENVIRONMENT:-production}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES:-1}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT:-}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-weak_secret_key}
      #
      PS1: "[$$RAILS_ENV] \\w \\$$ "

    depends_on:
      - postgres

volumes:
  postgres-data: